matrix:
  include:
    - name: "docker compose"
      language: generic
      services: docker
      script:
        - docker-compose build

    - name: "frontend"
      language: node_js
      node_js: "10"
      before_script:
        - cd frontend
        - echo "BACKEND_URL=\"http://127.0.0.1:8081\"" > .env.prod
        - yarn install
      script:
        - yarn build

    - name: "grpc server"
      language: java
      jdk: openjdk11
      install: mvn clean install -DskipTests -pl grpc-server -am -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"
      script: mvn test -pl grpc-server -am -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"

    - name: "nodejs proto files"
      language: node_js
      node_js: "node"
      before_script:
        - cd proto-node
        - yarn install
      script:
        - yarn build
      #deploy:
      #  skip_cleanup: true
      #  provider: npm
      #  email: $NPM_DPL_EMAIL
      #  api_key: $NPM_DPL_TOKEN

    - name: "server JS"
      language: node_js
      node_js: "8"
      before_script:
        - cd server-js
        - yarn install
      script:
        - yarn build

    - name: "shared JS"
      language: node_js
      node_js: "node"
      before_script:
        - cd shared-js
        - yarn install
      script:
        - yarn build
      #deploy:
      #  skip_cleanup: true
      #  provider: npm
      #  email: $NPM_DPL_EMAIL
      #  api_key: $NPM_DPL_TOKEN
